### ISSUE TITLE
不懂java，大佬能不能直接发布打包好的版本

### ISSUE THREAD

**Issue by charli2014** [zmatsh/NSS#1]
不懂java，windows下不懂怎么运行客户端，大佬能不能有空的时候打包一个win下的客户端。

**Comment by uk0** [comment]
里面有Jar包NSS-1.0-SNAPSHOT-jar-with-dependencies.jar 这个就是 直接 java -jar NSS-1.0-SNAPSHOT-jar-with-dependencies.jar 就行 conf是这个jar 的配置文件。

**Comment by charli2014** [comment]
![Uploading 2017-05-03_161655.png…]()
你好，我想问下这种界面是不是正确的，右边是没有的吧。

**Comment by charli2014** [comment]
<img width="282" alt="2017-05-03_161655" src="https://cloud.githubusercontent.com/assets/7960986/25652821/9969d600-301c-11e7-8623-f410d113fd5a.png">

你好，我想问下这种界面是不是正确的，右边是没有的吧。

**Comment by charli2014** [comment]
另外，我有点没看多服务端怎么运行。
是先编译，在运行吗
```
编译： mvn clean package
运行: java -jar NSS.jar
```

**Comment by charli2014** [comment]
另外，我有点没看懂服务端怎么运行。
是先编译，在运行吗
```
编译： mvn clean package
运行: java -jar NSS.jar
```
